TeX_SRCS = main.tex introduction.tex memory.tex

FoenixU.pdf: ${TeX_SRCS}
	pdflatex -jobname=Foenix-U-Guide main.tex

clean:
	-rm Foenix-U-Guide.pdf Foenix-U-Guide.aux Foenix-U-Guide.log
	-rm Foenix-U-Guide.lot Foenix-U-Guide.toc Foenix-U-Guide.out
